### ISSUE TITLE
Indicator does not update when slide slow

### ISSUE THREAD

**Issue by xlf2630** [ronaldsmartin/Material-ViewPagerIndicator#14]
I download and run the demo on my phone，when I slide pager from one side to another slowly,there are some case the indicator dot don`t update. The log show that lastKnownCurrentPage and position in PageListener::onPageSelected are equal. 
I think this maybe a bug.

**Comment by ronaldsmartin** [comment]
Thank you for finding this and pointing it out!

The same thing occurs on my Nexus 5x. I'll review your pull request now.

**Comment by ronaldsmartin** [comment]
Released in [v1.0.2](https://github.com/ronaldsmartin/Material-ViewPagerIndicator/releases/tag/1.0.2).
