### ISSUE TITLE
Gradle dependency not working 

### ISSUE THREAD

**Issue by asad1492** [ronaldsmartin/Material-ViewPagerIndicator#17]
Hello, 

 I am adding this compile `compile 'com.github.ronaldsmartin:Material-ViewPagerIndicator:1.0.2'` dependency to my gradle file. But its throwing an error Failed to resolve: com.github.ronaldsmartin:Material-ViewPagerIndicator:1.0.2

**Comment by ronaldsmartin** [comment]
Hi,

Did you add jitpack as a maven repository in your Gradle file first?
You may have seen it already, but the full install instructions for v1.0.2 are [available here](https://jitpack.io/#ronaldsmartin/Material-ViewPagerIndicator/1.0.2).

**Comment by ronaldsmartin** [comment]
Also:
Even if you have correctly added Jitpack as a repository, you may still run into issues installing dependencies through Jitpack if your Gradle version is not up-to-date.

As you can see [in this Jitpack issue](https://github.com/jitpack/jitpack.io/issues/424), a number of people had trouble using Jitpack dependencies with Gradle v2.10 and resolved them by updating to 2.11+.

**Comment by asad1492** [comment]
The first one worked. Thank you.
