### ISSUE TITLE
Small Circle Problem

### ISSUE THREAD

**Issue by yhaznedar** [ronaldsmartin/Material-ViewPagerIndicator#19]
Hello, 

Thanks for the gorgeous work, it was easy to integrate in my project. 

But the circles is so small (I think)
Is there any way to make bigger than it looks?

**Comment by ronaldsmartin** [comment]
Hi @yhaznedar,

Sorry for the delay in responding to you. Have you tried using the `app:dotRadius` property in your layout file? The [default is `3dp`](https://github.com/ronaldsmartin/Material-ViewPagerIndicator/blob/master/material-viewpagerindicator/src/main/java/com/itsronald/widget/IndicatorDotView.java#L53), so you can supply it with any larger dimension to increase circle sizes.

If you do this, you'll probably want to increase the `app:dotPadding` property as well.

For all current configuration options, please see this page on the wiki: https://github.com/ronaldsmartin/Material-ViewPagerIndicator/wiki/Advanced-Usage

Feel free to reach out if you have any more questions!

**Comment by yhaznedar** [comment]
You saved the day @ronaldsmartin, thank you good sir.
