### ISSUE TITLE
ViewPagerIndicator takes up space

### ISSUE THREAD

**Issue by vanniktech** [ronaldsmartin/Material-ViewPagerIndicator#23]
I'm using `com.itsronald.widget.ViewPagerIndicator` like this:

```xml
<com.google.android.gms.maps.MapView
      android:id="@+id/activitySpotDetailMapView"
      android:layout_width="0dp"
      android:layout_height="0dp"
      app:layout_constraintDimensionRatio="H,16:9"
      app:layout_constraintEnd_toEndOf="parent"
      app:layout_constraintStart_toStartOf="parent"
      app:layout_constraintTop_toTopOf="parent"
      />

<android.support.v4.view.ViewPager
    android:id="@+id/activitySpotDetailViewPager"
    android:layout_width="0dp"
    android:layout_height="0dp"
    app:layout_constraintDimensionRatio="H,16:9"
    app:layout_constraintEnd_toEndOf="parent"
    app:layout_constraintStart_toStartOf="parent"
    app:layout_constraintTop_toTopOf="parent"
    tools:background="#0f0"
    >
  <com.itsronald.widget.ViewPagerIndicator
      android:layout_width="match_parent"
      android:layout_height="@dimen/detail_page_indicator_height"
      android:layout_gravity="bottom|center_horizontal"
      android:background="@color/view_pager_dot_background"
      android:gravity="center_vertical"
      app:selectedDotColor="@color/view_pager_dot_active"
      app:unselectedDotColor="@color/view_pager_dot_inactive"
      />
</android.support.v4.view.ViewPager>
```

However the `ViewPagerIndicator` is not overlaying over the ViewPager items. Instead it takes up  the space (as a result the Map will then be rendered). As you can see in the screenshot I've got a ViewPager of Images and behind that a Map is shown.

![screen shot 2017-05-22 at 15 26 37](https://cloud.githubusercontent.com/assets/5759366/26311015/15af9732-3f03-11e7-820d-1adc5884bee3.png)

I'd like the Indicator to be rendered on top of the images so that the image bounds will be bigger and the map won't be shown. Is this in any way possible?

**Comment by ronaldsmartin** [comment]
Hi @vanniktech,

That is indeed weird. Are both your `MapView` and `ViewPager` children of another layout? What does the setup for that layout look like?

**Comment by vanniktech** [comment]
Yup they have a constraint layout as a parent. Nothing special to be honest c

**Comment by ronaldsmartin** [comment]
I've noticed you don't constrain the bottom of either view to its parent. Would that not be sufficient to have the ViewPager cover the MapView?

**Comment by vanniktech** [comment]
Well the indicator has a transparent background and therefore the map is shown underneath. A bottom constraint is not necessary.

**Comment by ronaldsmartin** [comment]
Oh, I see what you're saying. I'll see if I can replicate the effect and debug tonight. Thanks for reporting; we'll get to the bottom of this.

**Comment by vanniktech** [comment]
Let me know if you need any more information.

**Comment by ronaldsmartin** [comment]
I put together a simple layout and wasn't able to reproduce this error:

```xml
<?xml version="1.0" encoding="utf-8"?>
<android.support.constraint.ConstraintLayout 
    xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    android:id="@+id/activity_main"
    android:layout_width="match_parent"
    android:layout_height="match_parent">

    <View
        android:id="@+id/activitySpotDetailMapView"
        android:layout_width="0dp"
        android:layout_height="0dp"
        android:background="#1BF3AC"
        app:layout_constraintDimensionRatio="H,16:9"
        app:layout_constraintEnd_toEndOf="parent"
        app:layout_constraintStart_toStartOf="parent"
        app:layout_constraintTop_toTopOf="parent" />

    <android.support.v4.view.ViewPager
        android:id="@+id/view_pager"
        android:layout_width="0dp"
        android:layout_height="0dp"
        android:background="#BC000000"
        app:layout_constraintDimensionRatio="H,16:9"
        app:layout_constraintEnd_toEndOf="parent"
        app:layout_constraintStart_toStartOf="parent"
        app:layout_constraintTop_toTopOf="parent"
        >

        <com.itsronald.widget.ViewPagerIndicator
            android:layout_width="match_parent"
            android:layout_height="16dp"
            android:layout_gravity="bottom|center_horizontal"
            android:gravity="center_vertical"
            app:selectedDotColor="#FFF"
            app:unselectedDotColor="#11FFFFFF"/>

    </android.support.v4.view.ViewPager>
    
</android.support.constraint.ConstraintLayout>

```

I'm assuming this is at least somewhat like what you've done, minus the `MapView`. I also used simple background colors instead of setting up images in my `ViewPager`. Like I said, however, I'm getting the expected result where both the `ViewPager` and the first view in the layout have the same size, the `ViewPager` covers the first view completely, and the indicator is completely within the bounds of the `ViewPager`.

I'm wondering a couple of things:

1. Are you sure your images completely span the size of your `ViewPager`? Is it possible that your fragment layout is scaling them such that they're not taking up the full height of their parent?
2. If you give your `ViewPager` a background color, does the `ViewPagerIndicator` continue to appear to consume its own additional space?

Hope I can help you with this! Some extra context on your setup would shed more light on this issue.

**Comment by vanniktech** [comment]
From the preview I'm seeing the expected result with your constraint layout. However I think when adding views to the Pager you'll get mine.

1. They aren't. I still think that the indicator is taking up space. My guess is that ViewPager is laying the views out such as a LinearLayout would do and not like a FrameLayout (where we'll get the wanted stacking effect).
2. Yes it does. I gave the ViewPager a green background:

<img width="537" alt="screen shot 2017-05-25 at 12 27 52" src="https://cloud.githubusercontent.com/assets/5759366/26446730/9bbb9d00-4145-11e7-9a9d-5df215256af1.png">

**Comment by vanniktech** [comment]
You can also set a background color on the sample app and then you'll see that the dots won't get the background color:

```diff
diff --git a/app/src/main/res/layout/fragment_page.xml b/app/src/main/res/layout/fragment_page.xml
index 4ceb83e..020aa1c 100644
--- a/app/src/main/res/layout/fragment_page.xml
+++ b/app/src/main/res/layout/fragment_page.xml
@@ -22,6 +22,7 @@
     android:layout_width="match_parent"
     android:layout_height="match_parent"
     android:gravity="center"
+    android:background="#ff9"
     tools:context="com.itsronald.materialviewpagerindicatorsample.PageFragment">
 
     <TextView
```

**Comment by ronaldsmartin** [comment]
Thanks for the added info! Will continue to look at this tonight.

**Comment by vanniktech** [comment]
I'll close this now as this can be achieved now.
