### ISSUE TITLE
Will there be an AndroidX branch?

### ISSUE THREAD

**Issue by gaara87** [ronaldsmartin/Material-ViewPagerIndicator#31]

**Comment by gneokleous** [comment]
@ronaldsmartin I am also interested in this, I can do the migration if needed.

**Comment by ronaldsmartin** [comment]
Hi! To be honest, I haven't been doing Android for a couple of years and don't feel prepared to support AndroidX in the short term. @gneokleous, if you're interested in adding support for that, I'm happy to merge any pull requests you might make.

**Comment by giorgosneokleous93** [comment]
Created a PR @ronaldsmartin. If you have a release process and you don't have time to do it, I can have a look too.
